all:
	yacc -d bparser.y
	gcc -pedantic -Wall y.tab.c lexeme.c -ly -lfl -o parser
	lex lexer-standalone.lex
	gcc lex.yy.c -c
	gcc -pedantic -Wall lex.yy.o lexer.c lexeme.c -lfl -o lexer

lexer:
	lex lexer-standalone.lex
	gcc lex.yy.c -c
	gcc -pedantic -Wall lex.yy.o lexer.c lexeme.c -lfl -o lexer

clean:
	-rm -f lex.yy.c lex.yy.o
